name: "Pull Request Docs Check"

on: 
  pull_request:
    branches: [ master ]


jobs:

  docs:
    runs-on: ubuntu-latest
    steps:

    - name: Setup the environment
      uses: actions/checkout@v1

    - name: Create the new documentation
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "doc/"

    - name: Commit documentation changes
      run: |
        git clone https://github.com/mathLab/EZyRB.git --branch gh-pages --single-branch gh-pages
        cp -r docs/build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
